version: '3.8'
services:
  llhls-server:
    build:
      context: ./llhls-server
      dockerfile: Dockerfile
    container_name: llhls-server
    image: llhls-server
    ports:
      - "59919:59919"  # Expose port 80 on llhls-server
    volumes:
      - llhls-server-hls:/usr/share/nginx/html/hls
    restart: unless-stopped

  relay-server:
    build:
      context: ./relay-server
      dockerfile: Dockerfile
    container_name: relay-server
    image: relay-server
    ports:
       - "3001:3001"  # Expose WebSocket server
       -  "4001:4001"  # Expose ZeroMQ publisher
    volumes:
      - relay-config:/etc/relay-server
      - relay-server-logs:/var/log/relay-server  # Map to store logs locally
    restart: unless-stopped
    networks:
      - private  # Ensure this server joins the same network

volumes:
  llhls-server-hls:
    driver: local
  relay-config:
    driver: local
  relay-server-logs:
    driver: local

networks:
  private:
    driver: bridge
    external: true  # Use the already created private network