export class ConnectionPreviewData {
  public static data = [
    {
      id: 1,
      dtEvent: "2024-05-10",
      level: "Junior",
      program: "Woman",
      sport: "Football",
      status: "upcoming",
      title: "USA vs Canada",
      detail: {
        cityAddress: "123 Main Street",
        streetAdress: "Anytown",
        type: "Friendly Match",
      },
      year: 2024,
      venue: {
        location: "New York Stadium",
      },
      time: 1500,
      type: "live",
      countdown: "30 days, 10:20:15",
      activeDevice: [
        {
          id: 1,
          user: "Alice",
          location: "Stadium",
          deviceId: "ABC123",
          deviceType: "Mobile",
          network: "4G",
        },
        {
          id: 2,
          user: "Bob",
          location: "Home",
          deviceId: "XYZ789",
          deviceType: "Tablet",
          network: "WiFi",
        },
      ],
    },
    {
      id: 2,
      dtEvent: "2024-06-15",
      level: "Varsity",
      program: "Man",
      sport: "Cricket",
      status: "upcoming",
      title: "England vs Australia",
      detail: {
        cityAddress: "456 Elm Street",
        streetAdress: "Anytown",
        type: "Test Match",
      },
      year: 2024,
      venue: {
        location: "Lord's Cricket Ground",
      },
      time: 1000,
      type: "on-demand",
      countdown: "60 days, 05:40:30",
      activeDevice: [
        {
          id: 1,
          user: "Alice",
          location: "Stadium",
          deviceId: "ABC123",
          deviceType: "Mobile",
          network: "4G",
        },
        {
          id: 2,
          user: "Bob",
          location: "Home",
          deviceId: "XYZ789",
          deviceType: "Tablet",
          network: "WiFi",
        },
        {
          id: 3,
          user: "Charlie",
          location: "Stadium",
          deviceId: "DEF456",
          deviceType: "Smartphone",
          network: "5G",
        },
      ],
    },
    {
      id: 3,
      dtEvent: "2024-07-20",
      level: "Varsity",
      program: "Man",
      sport: "Tennis",
      status: "upcoming",
      title: "Wimbledon Final",
      detail: {
        cityAddress: "Church Road",
        streetAdress: "Wimbledon",
        type: "Grand Slam",
      },
      year: 2024,
      venue: {
        location: "All England Lawn Tennis and Croquet Club",
      },
      time: 1400,
      type: "live",
      countdown: "90 days, 03:15:00",
      activeDevice: [
        ,
        {
          id: 1,
          user: "Alice",
          location: "Stadium",
          deviceId: "ABC123",
          deviceType: "Mobile",
          network: "4G",
        },
        {
          id: 2,
          user: "Bob",
          location: "Home",
          deviceId: "XYZ789",
          deviceType: "Tablet",
          network: "WiFi",
        },
        {
          id: 3,
          user: "Charlie",
          location: "Stadium",
          deviceId: "DEF456",
          deviceType: "Smartphone",
          network: "5G",
        },
        {
          id: 4,
          user: "Diana",
          location: "Stadium",
          deviceId: "GHI789",
          deviceType: "Smartwatch",
          network: "Bluetooth",
        },
      ],
    },
    {
      id: 4,
      dtEvent: "2024-08-05",
      level: "Junior",
      program: "Woman",
      sport: "Swimming",
      status: "upcoming",
      title: "Olympic Women's 100m Freestyle Final",
      detail: {
        cityAddress: "1 Olympic Blvd",
        streetAdress: "Tokyo",
        type: "Olympic Event",
      },
      year: 2024,
      venue: {
        location: "Tokyo Aquatics Centre",
      },
      time: 1830,
      type: "live",
      countdown: "105 days, 08:30:45",
      activeDevice: [
        {
          id: 1,
          user: "Alice",
          location: "Stadium",
          deviceId: "ABC123",
          deviceType: "Mobile",
          network: "4G",
        },
        {
          id: 2,
          user: "Bob",
          location: "Home",
          deviceId: "XYZ789",
          deviceType: "Tablet",
          network: "WiFi",
        },
        {
          id: 3,
          user: "Charlie",
          location: "Stadium",
          deviceId: "DEF456",
          deviceType: "Smartphone",
          network: "5G",
        },
        {
          id: 4,
          user: "Diana",
          location: "Stadium",
          deviceId: "GHI789",
          deviceType: "Smartwatch",
          network: "Bluetooth",
        },
        {
          id: 5,
          user: "Emma",
          location: "Aquatics Centre",
          deviceId: "JKL012",
          deviceType: "Smartphone",
          network: "5G",
        },
        {
          id: 6,
          user: "Fiona",
          location: "Home",
          deviceId: "MNO345",
          deviceType: "Tablet",
          network: "WiFi",
        },
      ],
    },
    {
      id: 5,
      dtEvent: "2024-09-10",
      level: "Varsity",
      program: "Man",
      sport: "Golf",
      status: "upcoming",
      title: "Ryder Cup",
      detail: {
        cityAddress: "PGA Blvd",
        streetAdress: "Havenwood",
        type: "Golf Tournament",
      },
      year: 2024,
      venue: {
        location: "Hazeltine National Golf Club",
      },
      time: 8000,
      type: "live",
      countdown: "150 days, 14:00:20",
      activeDevice: [
        {
          id: 7,
          user: "George",
          location: "Hazeltine National Golf Club",
          deviceId: "PQR678",
          deviceType: "Smartphone",
          network: "5G",
        },
        {
          id: 1,
          user: "Alice",
          location: "Stadium",
          deviceId: "ABC123",
          deviceType: "Mobile",
          network: "4G",
        },
        {
          id: 2,
          user: "Bob",
          location: "Home",
          deviceId: "XYZ789",
          deviceType: "Tablet",
          network: "WiFi",
        },
        {
          id: 3,
          user: "Charlie",
          location: "Stadium",
          deviceId: "DEF456",
          deviceType: "Smartphone",
          network: "5G",
        },
        {
          id: 4,
          user: "Diana",
          location: "Stadium",
          deviceId: "GHI789",
          deviceType: "Smartwatch",
          network: "Bluetooth",
        },
      ],
    },
  ];
}
