export class MetaTypesDummy {
    public static data = {
        "Absolute URI":"GET::/api/meta-types",
        "Gateway Response":{
           "count":7,
           "result":[
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":4
                 },
                 {
                    "field":"name",
                    "type":1,
                    "value":"Sport"
                 },
                 {
                    "field":"values",
                    "type":1,
                    "value":"[\"Archery\",\"Badminton\",\"Baseball\",\"Basketball\",\"Bowling\",\"Boxing\",\"Camping\",\"Canoeing\",\"Climbing\",\"Cricket\",\"Curling\",\"Cycling\",\"Fencing\",\"Fishing\",\"Fitness\",\"Football\",\"Figure Skating\",\"Gymnastics\",\"Hang Gliding\",\"High Jumping\",\"Hockey\"]"
                 },
                 {
                    "field":"key",
                    "type":1,
                    "value":"SPORT"
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":1
                 },
                 {
                    "field":"name",
                    "type":1,
                    "value":"Program"
                 },
                 {
                    "field":"values",
                    "type":1,
                    "value":"[\"Woman\",\"Man\"]"
                 },
                 {
                    "field":"key",
                    "type":1,
                    "value":"PROGRAM"
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":5
                 },
                 {
                    "field":"name",
                    "type":1,
                    "value":"Location"
                 },
                 {
                    "field":"values",
                    "type":1,
                    "value":"[\"Press Box\",\"Sideline\"]"
                 },
                 {
                    "field":"key",
                    "type":1,
                    "value":"LOCATION"
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":6
                 },
                 {
                    "field":"name",
                    "type":1,
                    "value":"Device Type"
                 },
                 {
                    "field":"values",
                    "type":1,
                    "value":"[\"Camcorder\",\"Mobile\",\"iPad\",\"Tablet\"]"
                 },
                 {
                    "field":"key",
                    "type":1,
                    "value":"DEVICETYPE"
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":7
                 },
                 {
                    "field":"name",
                    "type":1,
                    "value":"Event Type"
                 },
                 {
                    "field":"values",
                    "type":1,
                    "value":"[\"Scheduled\",\"On demand\"]"
                 },
                 {
                    "field":"key",
                    "type":1,
                    "value":"EVENTTYPE"
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":3
                 },
                 {
                    "field":"name",
                    "type":1,
                    "value":"Level"
                 },
                 {
                    "field":"values",
                    "type":1,
                    "value":"[\"Varsity\",\"Junior Varsity\",\"Senior\",\"Sophomore\"]"
                 },
                 {
                    "field":"key",
                    "type":1,
                    "value":"LEVEL"
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":8
                 },
                 {
                    "field":"name",
                    "type":1,
                    "value":"Title"
                 },
                 {
                    "field":"values",
                    "type":1,
                    "value":"[\"Head Coach\",\"ASSISTANT HEAD COACH\",\"ASSISTANT COACH\",\"RECRUITING COORDINATOR\"]"
                 },
                 {
                    "field":"key",
                    "type":1,
                    "value":"TITLE"
                 }
              ]
           ]
        }
     }
}