export class PlayersDummy {
    public static data = {
        "Absolute URI":"GET::/api/players",
        "Gateway Response":{
           "count":4,
           "result":[
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":374
                 },
                 {
                    "field":"sport",
                    "type":1,
                    "value":"Basketball"
                 },
                 {
                    "field":"level",
                    "type":1,
                    "value":"College"
                 },
                 {
                    "field":"program",
                    "type":1,
                    "value":"Men"
                 },
                 {
                    "field":"year",
                    "type":1,
                    "value":"2024"
                 },
                 {
                    "field":"first_name",
                    "type":1,
                    "value":"John"
                 },
                 {
                    "field":"last_name",
                    "type":1,
                    "value":"Doe"
                 },
                 {
                    "field":"hometown",
                    "type":1,
                    "value":"Springfield"
                 },
                 {
                    "field":"height",
                    "type":0,
                    "value":190
                 },
                 {
                    "field":"weight",
                    "type":0,
                    "value":85
                 },
                 {
                    "field":"high_school",
                    "type":1,
                    "value":"Springfield High"
                 },
                 {
                    "field":"prev_school",
                    "type":1,
                    "value":"West High"
                 },
                 {
                    "field":"majors",
                    "type":1,
                    "value":"Sports Management"
                 },
                 {
                    "field":"mobile",
                    "type":1,
                    "value":"123-456-7890"
                 },
                 {
                    "field":"email",
                    "type":1,
                    "value":"john.doe@example.com"
                 },
                 {
                    "field":"city",
                    "type":1,
                    "value":"Springfield"
                 },
                 {
                    "field":"social_links",
                    "type":5,
                    "value":{
                       "facebook":"https://facebook.com/johndoe",
                       "instagram":"https://www.instagram.com/johndoe/",
                       "twitter":"https://twitter.com/johndoe",
                       "youtube":"https://youtube.com/johndoe"
                    }
                 },
                 {
                    "field":"picture",
                    "type":1,
                    "value":"https://example.com/images/john.jpg"
                 },
                 {
                    "field":"bio",
                    "type":1,
                    "value":"Talented basketball player with strong leadership skills."
                 },
                 {
                    "field":"stats",
                    "type":1,
                    "value":"Average 20 points per game in 2023 season."
                 },
                 {
                    "field":"media",
                    "type":5,
                    "value":{
                       "highlights":[
                          "https://example.com/media/game1.mp4",
                          "https://example.com/media/game2.mp4"
                       ]
                    }
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":376
                 },
                 {
                    "field":"sport",
                    "type":1,
                    "value":"Tennis"
                 },
                 {
                    "field":"level",
                    "type":1,
                    "value":"Junior"
                 },
                 {
                    "field":"program",
                    "type":1,
                    "value":"Woman"
                 },
                 {
                    "field":"year",
                    "type":1,
                    "value":"2024"
                 },
                 {
                    "field":"first_name",
                    "type":1,
                    "value":"Alice"
                 },
                 {
                    "field":"last_name",
                    "type":1,
                    "value":"Johnson"
                 },
                 {
                    "field":"hometown",
                    "type":1,
                    "value":"Lakeside"
                 },
                 {
                    "field":"height",
                    "type":0,
                    "value":175
                 },
                 {
                    "field":"weight",
                    "type":0,
                    "value":70
                 },
                 {
                    "field":"high_school",
                    "type":1,
                    "value":"Lakeside High"
                 },
                 {
                    "field":"prev_school",
                    "type":1,
                    "value":"East High"
                 },
                 {
                    "field":"majors",
                    "type":1,
                    "value":"Kinesiology"
                 },
                 {
                    "field":"mobile",
                    "type":1,
                    "value":"555-123-4567"
                 },
                 {
                    "field":"email",
                    "type":1,
                    "value":"alice.johnson@example.com"
                 },
                 {
                    "field":"city",
                    "type":1,
                    "value":"Lakeside"
                 },
                 {
                    "field":"social_links",
                    "type":5,
                    "value":{
                       "facebook":"https://facebook.com/alicejohnson",
                       "instagram":"https://www.instagram.com/alicejohnson/",
                       "twitter":"https://twitter.com/alicejohnson",
                       "youtube":"https://youtube.com/alicejohnson"
                    }
                 },
                 {
                    "field":"picture",
                    "type":1,
                    "value":"https://example.com/images/alice.jpg"
                 },
                 {
                    "field":"bio",
                    "type":1,
                    "value":"Young tennis player with a powerful serve."
                 },
                 {
                    "field":"stats",
                    "type":1,
                    "value":"Won 10 tournaments in 2023 season."
                 },
                 {
                    "field":"media",
                    "type":5,
                    "value":{
                       "highlights":[
                          "https://example.com/media/match3.mp4",
                          "https://example.com/media/match4.mp4"
                       ]
                    }
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":375
                 },
                 {
                    "field":"sport",
                    "type":1,
                    "value":"Soccer"
                 },
                 {
                    "field":"level",
                    "type":1,
                    "value":"Professional"
                 },
                 {
                    "field":"program",
                    "type":1,
                    "value":"Men"
                 },
                 {
                    "field":"year",
                    "type":1,
                    "value":"2024"
                 },
                 {
                    "field":"first_name",
                    "type":1,
                    "value":"Jane"
                 },
                 {
                    "field":"last_name",
                    "type":1,
                    "value":"Smith"
                 },
                 {
                    "field":"hometown",
                    "type":1,
                    "value":"Rivertown"
                 },
                 {
                    "field":"height",
                    "type":0,
                    "value":165
                 },
                 {
                    "field":"weight",
                    "type":0,
                    "value":60
                 },
                 {
                    "field":"high_school",
                    "type":1,
                    "value":"Rivertown High"
                 },
                 {
                    "field":"prev_school",
                    "type":1,
                    "value":"North High"
                 },
                 {
                    "field":"majors",
                    "type":1,
                    "value":"Physical Education"
                 },
                 {
                    "field":"mobile",
                    "type":1,
                    "value":"987-654-3210"
                 },
                 {
                    "field":"email",
                    "type":1,
                    "value":"jane.smith@example.com"
                 },
                 {
                    "field":"city",
                    "type":1,
                    "value":"Rivertown"
                 },
                 {
                    "field":"social_links",
                    "type":5,
                    "value":{
                       "facebook":"https://facebook.com/janesmith",
                       "instagram":"https://www.instagram.com/janesmith/",
                       "twitter":"https://twitter.com/janesmith",
                       "youtube":"https://youtube.com/janesmith"
                    }
                 },
                 {
                    "field":"picture",
                    "type":1,
                    "value":"https://example.com/images/jane.jpg"
                 },
                 {
                    "field":"bio",
                    "type":1,
                    "value":"Dynamic soccer player known for her speed and agility."
                 },
                 {
                    "field":"stats",
                    "type":1,
                    "value":"Scored 15 goals in the 2023 season."
                 },
                 {
                    "field":"media",
                    "type":5,
                    "value":{
                       "highlights":[
                          "https://example.com/media/match1.mp4",
                          "https://example.com/media/match2.mp4"
                       ]
                    }
                 }
              ],
              [
                 {
                    "field":"id",
                    "type":0,
                    "value":379
                 },
                 {
                    "field":"sport",
                    "type":1,
                    "value":"Baseball"
                 },
                 {
                    "field":"level",
                    "type":1,
                    "value":"College"
                 },
                 {
                    "field":"program",
                    "type":1,
                    "value":"Men"
                 },
                 {
                    "field":"year",
                    "type":1,
                    "value":"2024"
                 },
                 {
                    "field":"first_name",
                    "type":1,
                    "value":"Derek"
                 },
                 {
                    "field":"last_name",
                    "type":1,
                    "value":"Jeter"
                 },
                 {
                    "field":"hometown",
                    "type":1,
                    "value":"Springfield"
                 },
                 {
                    "field":"height",
                    "type":0,
                    "value":190
                 },
                 {
                    "field":"weight",
                    "type":0,
                    "value":85
                 },
                 {
                    "field":"high_school",
                    "type":1,
                    "value":"Springfield High"
                 },
                 {
                    "field":"prev_school",
                    "type":1,
                    "value":"West High"
                 },
                 {
                    "field":"majors",
                    "type":1,
                    "value":"Sports Management"
                 },
                 {
                    "field":"mobile",
                    "type":1,
                    "value":"6543206754"
                 },
                 {
                    "field":"email",
                    "type":1,
                    "value":"derek.jeter@example.com"
                 },
                 {
                    "field":"city",
                    "type":1,
                    "value":"Springfield"
                 },
                 {
                    "field":"social_links",
                    "type":5,
                    "value":{
                       "facebook":"https://facebook.com/derek",
                       "instagram":"https://www.instagram.com/derek/",
                       "twitter":"https://twitter.com/derek",
                       "youtube":"https://youtube.com/derek"
                    }
                 },
                 {
                    "field":"picture",
                    "type":1,
                    "value":"https://example.com/images/derek.jpg"
                 },
                 {
                    "field":"bio",
                    "type":1,
                    "value":"Talented basketball player with strong leadership skills."
                 },
                 {
                    "field":"stats",
                    "type":1,
                    "value":"Average 20 points per game in 2023 season."
                 },
                 {
                    "field":"media",
                    "type":5,
                    "value":{
                       "highlights":[
                          "https://example.com/media/game1.mp4",
                          "https://example.com/media/game2.mp4"
                       ]
                    }
                 }
              ]
           ]
        }
     }
}